PLAYG-64 댓글생성,수정,삭제 조건문추가 , 댓글삭제여부컬럼추가
playground-PLYG/playground pull request #73
Opened 2024-06-12 00:20 UTC by kimsoohwan6198

2024-06-12 00:50 UTC, hsm0711 requested changes
댓글삭제 소스 확인 필요

2024-06-13 00:14 UTC, hsm0711 requested changes
DynamicInsert, DynamicUpdate방법 또는 select 후 변경 컬럼 update를 사용하는 방안 중 불필요하게 혼용해서 사용할 필요가 없는 경우 통일해서 사용할 것

2024-06-13 01:06 UTC, kimsoohwan6198 commented
> DynamicInsert, DynamicUpdate방법 또는 select 후 변경 컬럼 update를 사용하는 방안 중 불필요하게 혼용해서 사용할 필요가 없는 경우 통일해서 사용할 것


댓글 insert시 tb_comment 테이블의 delete_at(댓글사용여부) default "N" 값이 들어가기 위해  DynamicInsert를 사용하였다.
DynamicInsert를 사용 안하면 delete_at의 null값이 들어가기 때문에 null인 필드를 제외하기 위해 DynamicInsert를 사용함
ex1) insert into tb_comment (cmnt_sn, ntt_sn, cmnt_cn, delete_at) values ('dfdfdsf', 'adfdf', 'dfdafdf', null);  
ex2) insert into tb_comment (cmnt_sn, ntt_sn, cmnt_cn) values ('dfdfdsf', 'adfdf', 'dfdafdf');   // DynamicInsert를 사용했을때 insert

2024-06-13 01:41 UTC, hsm0711 approved these changes

2024-06-13 01:49 UTC, merged